# nixpacks.toml

[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
# Тепер .sln лежить у корені, тому шлях не потрібен
cmds = ["dotnet publish TestCarBot.sln -c Release -o out"]

[start]
cmd = "dotnet out/TestCarBot.dll"