# nixpacks.toml

# Вказуємо версію .NET SDK
[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = ["dotnet publish CarInsuranceSaleBot.sln -c Release -o out"]

[start]
cmd = "dotnet out/TestCarBot.dll"